#应用名称
spring:
  application:
    name: bany-game
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bany-game
    username: root
    password: root
    max-idle: 20
    max-wait: 10
    min-idle: 10
    initial-size: 10

#应用端口
server:
  port: 80

#配置mybatis plugs
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug




